language: php

addons:
  apt:
    packages:
      - libuv1
      - php-pear

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    - pecl install uv-beta
    - php -m
    - composer self-update

after_success:
    - bash <(curl -s https://codecov.io/bash)

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
