# GitHub Action for PHP with extensions
name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Linux CI
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          extensions: mbstring, simplexml, dom, xdebug, uv-beta
          coverage: xdebug
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage/phpunit/clover.xml
      - name: Submit code coverage
        if: ${{ success() }} || ${{ failure() }}
        run: bash <(curl -s https://codecov.io/bash)

  linux_php81:
      name: Linux CI - no libuv
      runs-on: ubuntu-latest
      continue-on-error: true
      strategy:
        fail-fast: false
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup PHP, with composer and extensions
          uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
          with:
            php-version: '8.1'
            extensions: mbstring, simplexml, dom
        - name: Install dependencies
          run: composer install
        - name: Test with phpunit
          run: vendor/bin/phpunit -d zend.enable_gc=0 --coverage-clover=coverage/phpunit/clover.xml
        - name: Submit code coverage
          if: ${{ success() }} || ${{ failure() }}
          run: bash <(curl -s https://codecov.io/bash)
