# GitHub Action for PHP with extensions
name: Coroutine

on: [push, pull_request]

jobs:
  linux:
    name: Linux CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install libuv and PHP build tools
        run: |
          sudo apt update
          sudo apt-get install libuv1-dev php-pear
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          extensions: mbstring, simplexml, dom, xdebug
      - name: Build and install PHP-UV extension
        run: |
          sudo pecl channel-update pecl.php.net
          sudo pecl install uv-beta
          sudo cp -f /usr/lib/php/20190902/uv.so /usr/lib/php/20170718/uv.so
      - name: Add uv.so to php.ini
        run: sudo echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)

  windows:
    name: Windows CI
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php: ['7.3']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: pecl
        extensions: mbstring, simplexml, curl, dom, xdebug, sockets, fileinfo, openssl, uv-beta
      env:
        PHPTS: ts # specify ts or nts
    - name: Install dependencies
      run: composer install
    - name: Test with phpunit
      run: vendor\bin\phpunit --coverage-clover=coverage.xml
    - name: Submit code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
